apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: force-rw-disk-webhook
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          service.beta.openshift.io/serving-cert-secret-name: force-rw-disk-webhook-tls
  - target:
      kind: MutatingWebhookConfiguration
      name: force-rw-disk-webhook
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          service.beta.openshift.io/inject-cabundle: "true"
